# Generated by Django 4.1.5 on 2023-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_note', models.ImageField(upload_to='')),
                ('pred', models.CharField(max_length=50)),
            ],
        ),
    ]
